name: PDF to PNG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Install ghostscript
        run: sudo apt-get update && sudo apt install ghostscript

      - name: Change ImageMagick security policy
        run: |
          DQT='"' 
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read\|write${DQT} pattern=${DQT}PDF${DQT}"
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: .
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Rename PDF
        run: mv main.pdf Zhu_Harry_Resume.pdf

      - name: Convert PDF to PNG
        run: |
          convert -density 300 -background white -alpha off Zhu_Harry_Resume.pdf -quality 90 Zhu_Harry_Resume.png

      - name: Commit and Push PNG
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Zhu_Harry_Resume.png
          git commit -m "[bot] Update resume based on new user revisions"
          git push
